budgetcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.Home.as_view(), name='home'),
  path('about/', views.about, name='about'),
  path('months/', views.months_index, name='months_index'),
  path('months/<int:month_id>/', views.months_detail, name='months_detail'),
  path('months/create/', views.MonthCreate.as_view(), name='months_create'),
  path('months/<int:pk>/delete/', views.MonthDelete.as_view(), name='months_delete'),
  path('months/<int:month_id>/add_expense/', views.add_expense, name='add_expense'),
  path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

WORTHIT = (
  ('Y', 'Yes'),
  ('N', 'No'),
)
RECURRING = {
  ('Y', 'Yes'),
  ('N', 'No'), 
}
PAID = {
  ('Y', 'Yes'),
  ('N', 'No'), 
}

class Month(models.Model):
  name = models.CharField(max_length=100)
  year = models.CharField(max_length=100)
  budget = models.IntegerField()
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('months_detail', kwargs={'month_id': self.id})

class Expense(models.Model):
  date = models.DateField()
  price = models.IntegerField()
  reason = models.TextField(max_length=300)
  worthit = models.CharField(
    max_length=1,
    choices=WORTHIT,
    )
  recurring = models.CharField(
    max_length=1,
    choices=RECURRING,
    )
  paid = models.CharField(
    max_length=1,
    choices=PAID,
    # default=PAID[0][0]
    )

  month = models.ForeignKey(Month, on_delete=models.CASCADE)
  def __str__(self):
    # Nice method for obtaining the friendly value of a Field.choice
    return f"{self.get_worthit_display()} on {self.date}"

  def __str__(self):
    # Nice method for obtaining the friendly value of a Field.choice
    return f"{self.get_recurring_display()} on {self.date}"

  def __str__(self):
    # Nice method for obtaining the friendly value of a Field.choice
    return f"{self.get_paid_display()} on {self.date}"
class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Expense

class ExpenseForm(ModelForm):
  class Meta:
    model = Expense
    fields = ['date', 'price', 'reason', 'worthit', 'recurring', 'paid']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Month
from .forms import ExpenseForm
from django.contrib.auth.views import LoginView



# Define the home view
class Home(LoginView):
  template_name = 'home.html'

def about(request):
  return render(request, 'about.html')

class Months:  # Note that parens are optional if not inheriting from another class
  def __init__(self, name, budget, year):
    self.name = name
    self.budget = budget
    self.year = year

@login_required
def months_index(request):
  months = Month.objects.filter(user=request.user)
  months = Month.objects.all()
  return render(request, 'months/index.html', { 'months': months })


def months_detail(request, month_id):
  month = Month.objects.get(id=month_id)
  expense_form = ExpenseForm()
  return render(request, 'months/detail.html', {
    'month': month, 'expense_form': expense_form
  
  })


class MonthCreate(LoginRequiredMixin,CreateView):
  model = Month
  fields = 'name', 'year', 'budget'
  success_url = '/months/'
  def form_valid(self, form):
    form.instance.user = self.request.user  
    return super().form_valid(form)

class MonthDelete(LoginRequiredMixin,DeleteView):
  model = Month
  success_url = '/months/'

@login_required  
def add_expense(request, month_id):
  form = ExpenseForm(request.POST)
  if form.is_valid():
    new_expense = form.save(commit=False)
    new_expense.month_id = month_id
    new_expense.save()
  return redirect('months_detail', month_id=month_id)


def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('months_index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<h1>The Log It app</h1>
<hr/>
<p>
  The Log it app is an app that will help you keep track of your expenses for each month. This will help you budget and reach your saving goal. This app will also help you keep track of things the reason for the expense and much more. Click on the button add a month to start. Select the month you want to start and start budgeting.</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="" />
    <title>LOG IT</title>
    <link rel="shortcut icon" type="image/jpg" href="{% static 'images/red-bag.png'%}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    {% block head %} {% endblock %}
  {% comment %} </head>
  <body>
    <nav>
      <div class="nav-container">
        <input type="checkbox" />
        <div class="nav-group">
          <div class="hamburger-icon">
            <i class="fa fa-bars" aria-hidden="true"></i>
          </div>
          <div class="nav-logo">
            <a href="">
              <img
                class="nav-img"
                src="{% static 'images/pngwing.com.png' %}"
                alt="dollar sign"
            /></a>
          </div>
        </div>
        <div class="nav-links">
          <ul>
            {% if user.is_authenticated %}
            <li><a href="{% url 'months_index'%}">All months</a></li>
            <li><a href="{% url 'months_create'%}">Add A month</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'logout' %}">Log out</a></li>
            {% else %}
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'home' %}">Login</a></li>
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <div class="dot"></div>

            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="header-logo-container">{% endcomment %}</div>

    <header>
      <nav class="navMenu">
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'months_index'%}">All months</a></li>
          <li><a href="{% url 'months_create'%}">Add A month</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'logout' %}">Log out</a></li>
          {% else %}
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'home' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <div class="dot"></div>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}

{% block content %}

{% if not user.is_authenticated %}
  <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}">
      <button type="submit" class="btn submit">Login</button>
    </form>
  </section>
{% endif %}

{% endblock %}

main_app/templates/main_app/month_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Month?</h1>
  <img src="{% static 'images/time.png' %}" alt="Alarm clock"/>
</div>
<h2>Are you sure you want to delete {{ object.name }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'months_detail' month.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/month_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  <h1 class="fas fa-calendar-week"> Add a Month </h1>
</div>
{% comment %} 
  Leaving the action empty makes the form post to the same url used to display it
{% endcomment %}
<form action="" method="post" class="form-container">

  {% csrf_token %}
  <table>
    {% comment %}
      Render the inputs inside of <tr>s & <td>s
    {% endcomment %}
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/months/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  href="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.css" 
  rel="stylesheet" 
/>
<link rel="stylesheet" href="{% static 'css/mcdp.css' %}">
<script 
  src="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.js"
>
</script>
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static 'css/month-detail.css' %}"
/>
<link rel="stylesheet" href="{% static 'css/mcdp.css' %}">
<script defer src="{% static 'js/month-detail.js' %}"></script>
</script>
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static 'css/month-detail.css' %}"
/>
{% endblock %}

{% block content %}

<section class="cat-container">
  <div class="cat-img">
    <img 
      src="{% static 'images/us-dollar.png' %}" 
      alt="A skater boy month"
    >
  </div>
  <div class="cat-details">
    <h1>The break down for {{ month.name }}.</h1>
      <h2> In the year {{ month.year }} {{ month.breed }}</h2>
      <h2>The goal for this month is to save $ {{ month.budget }} .</h2>
  </div>
      <a href="{% url 'months_delete' month.id %}" class="btn danger">Delete</a>
</section>
<div class="feedings-toy-container">
  <section class="feedings">
    <div class="subsection-title">
      <h2>Expenses</h2>
      <img 
        src="{% static 'images/dollar-sign.png' %}" 
        alt="An ice cream cone cat"
      />
      <img 
        src="{% static 'images/money-bag-3.png' %}"
        alt="A cat as onigiri"
      />
      <img 
        src="{% static 'images/money-bag-1.png' %}" 
        alt="A kabob of kittens"
      />
    </div>
    <form
      action="{% url 'add_expense' month.id %}" 
      method="post" 
      class="subsection-content"
    >
      {% csrf_token %}
      {{ expense_form.as_p }}
      <button type="submit" class="btn submit">Add Expenses</button>
    </form>
    <div class="table-container">
      <h3>Past expense</h3>
    <table class="expense-table">
      <thead>
      <tr>
      <th>Date</th>
      <th>price</th>
      <th>reason</th>
      <th>worth it?</th>
      <th>recurring</th>
      <th>paid</th>
      </tr>
      </thead>
      <tbody>
          <tr>
          {% for expense in month.expense_set.all %}
            <td>{{expense.date}}</td>
            <td>{{expense.price}}</td>
            <td>{{expense.reason}}</td>
            <td>{{expense.get_worthit_display}}</td>
            <td>{{expense.get_recurring_display}}</td>
            <td>{{expense.get_paid_display}}</td>
          </tr>
        {% endfor %}
        
    
    
    

      </tbody>
    </table>
  </div>
    
  </section>
</div>


{% endblock %}

main_app/templates/months/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/month-index.css' %}"/>
{% endblock %}

{% block content %}

<section class="page-header">
  <h1>Months</h1>
  <img src="{% static 'images/banknotes.png' %}" alt="Banknotes" />
  <img src="{% static 'images/bitcoin.png' %}" alt="Bitcoin" />
  <img src="{% static 'images/red-bag.png' %}" alt="red bag" />
  <img src="{% static 'images/us-dollar.png' %}" alt="dollar"/>
</section>
<section class="card-container">
  {% for month in months %}
  <div class="card">
    <a href="{% url 'months_detail' month.id %}">
      <div class="card-content">
        <div class="card-img-container">
          <img 
            src="{% static 'images/money-world.png' %}" 
            alt="money world"
          >
        </div>
        <div class = "title1">
        <h2 class="card-title">{{ month.name }}</h2>
        {% if month.name > 0 %}
        {% else %}
          <p class= "p">The budget for  {{ month.name }} is {{ month.budget }}</p>
          <p>{{ month.year }}</p>
          </div>
        {% endif %}
      </a>
      </div>
    </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/money-bag-3.png' %}" alt="A cat using a computer"/>
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}